### ISSUE TITLE
Well done!  and a license question?

### ISSUE THREAD

**Issue by RobTillaart** [tomverbeure/parallel2usb#1]
Hi Tom,

Saw a reference to your project on HackaDay and I love it, well done!

Writing (Arduino) libraries is one of my jobs and I want to make a reference to your project in my Parallel Printer library. (OK?)
- https://github.com/RobTillaart/ParallelPrinter

It is the other side of your project - think of a driver - to be able to use old printers as an output device. 
In fact the project you made is on my todo list. (maybe it will drop off ;)

Question: you do not have a license set with your project, is this on purpose or?

**Comment by tomverbeure** [comment]
Hi Rob,

Feel free to use this any way you want!

I've added a license.

Tom
